/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zhuoweizhang_goom_Goom */

#ifndef _Included_net_zhuoweizhang_goom_Goom
#define _Included_net_zhuoweizhang_goom_Goom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zhuoweizhang_goom_Goom
 * Method:    nativeGoomInit
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_net_zhuoweizhang_goom_Goom_nativeGoomInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_zhuoweizhang_goom_Goom
 * Method:    nativeSetResolution
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_goom_Goom_nativeSetResolution
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_zhuoweizhang_goom_Goom
 * Method:    nativeGoomUpdate
 * Signature: (J[SIFLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_zhuoweizhang_goom_Goom_nativeGoomUpdate
  (JNIEnv *, jclass, jlong, jshortArray, jint, jfloat, jstring, jstring);

/*
 * Class:     net_zhuoweizhang_goom_Goom
 * Method:    nativeGoomSetScreenbuffer
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_zhuoweizhang_goom_Goom_nativeGoomSetScreenbuffer
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     net_zhuoweizhang_goom_Goom
 * Method:    nativeGoomClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_goom_Goom_nativeGoomClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
